theme = "catppuccin_mocha"

[editor.soft-wrap]
enable = true

[editor.lsp]
auto-signature-help = false 

[keys.insert]
"C-," = "signature_help" # DOES NOT WORK

[keys.normal]
"X" = "extend_line_up"

[editor.file-picker]
hidden = false
